apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 8000
  selector:
    app: vote
  
